name: flake-lock-update

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 18 * * 3' # Every thursday on 18:00

jobs:
  update-flake-lock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 1
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v19
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v27
        with:
          git-committer-name: "github-actions[bot]"
          git-committer-email: "github-actions[bot]@users.noreply.github.com"
          pr-title: "flake.lock: Update"
          pr-assignees: nukdokplex
          token: ${{ secrets.GH_TOKEN_FOR_FLAKE_LOCK_UPDATE }}
